services:
  # Database
  conscious_db:
    build:
      context: ./infra/Dockerfile.d
      dockerfile: postgres
    env_file:
      - ./infra/env.d/postgres
    volumes:
      - .data/postgres:/var/lib/postgresql/data
      # Initialization script(s), runs only on first creation
      - ./infra/initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    shm_size: 1gb
    restart: unless-stopped

  # FastAPI Development
  dev-backend:
    build:
      context: ./app/backend
      dockerfile: Dockerfile-dev
    env_file:
      - ./infra/env.d/ai
      - ./infra/env.d/postgres
      - ./infra/env.d/backend
      - ./infra/env.d/.private
    volumes:
      - ./app/backend:/app
      - .data/cache/dspy:/cache/dspy
    ports:
      - "8000:8000"
    restart: no

  # SvelteKit Development
  dev-frontend:
    build:
      context: ./app/frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    env_file:
      - ./infra/env.d/backend
      - ./infra/env.d/frontend
      - ./infra/env.d/.private
    volumes:
      - ./app/frontend:/app
    restart: no

  # SvelteKit Production
  prod-frontend:
    build:
      context: ./app/frontend
      dockerfile: Dockerfile.prod
    env_file:
      - ./infra/env.d/backend
      - ./infra/env.d/frontend
      - ./infra/env.d/.private
    environment:
      # CSRF: tell SvelteKit about the request protocol and host, from which it can construct the origin URL
      # Reference: https://github.com/sveltejs/kit/blob/main/documentation/docs/25-build-and-deploy/40-adapter-node.md
      PROTOCOL_HEADER: x-forwarded-proto
      HOST_HEADER: x-forwarded-host
    restart: unless-stopped

  # Nginx Reverse Proxy
  nginx:
    image: nginx:stable-alpine
    ports:
      - '80:80'
    volumes:
      # Mount the Nginx configuration file (read-only)
      - ./infra/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - prod-frontend
    restart: unless-stopped