services:
  # PostgreSQL Database Production
  prod-database:
    build:
      context: ./app/database
      dockerfile: Dockerfile
    env_file:
      - ./infra/env.d/prod
      - ./infra/env.d/database
    volumes:
      - .data/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    shm_size: 1gb
    profiles: ["prod"]
    networks:
      - prod_network
    restart: unless-stopped

  # FastAPI Backend Production
  prod-backend:
    build:
      context: ./app/backend
      dockerfile: Dockerfile
    env_file:
      - ./infra/env.d/prod
      - ./infra/env.d/ai
      - ./infra/env.d/backend
      - ./infra/env.d/database
      - ./infra/env.d/.private
    volumes:
      - .data/cache/dspy:/cache/dspy
    ports:
      - "8000:8000"
    depends_on:
      - prod-database
    profiles: ["prod"]
    networks:
      - prod_network
    restart: unless-stopped

  # SvelteKit Frontend Production
  prod-frontend:
    build:
      context: ./app/frontend
      dockerfile: Dockerfile
    env_file:
      - ./infra/env.d/prod
      - ./infra/env.d/backend
      - ./infra/env.d/frontend
      - ./infra/env.d/.private
    environment:
      # CSRF: tell SvelteKit about the request protocol and host, from which it can construct the origin URL
      # Reference: https://github.com/sveltejs/kit/blob/main/documentation/docs/25-build-and-deploy/40-adapter-node.md
      PROTOCOL_HEADER: x-forwarded-proto
      HOST_HEADER: x-forwarded-host
    depends_on:
      - prod-backend
    profiles: ["prod"]
    networks:
      - prod_network
    restart: unless-stopped

  # Nginx Reverse Proxy Production
  prod-nginx:
    build:
      context: ./app/nginx
      dockerfile: Dockerfile
    ports:
      - '80:80'
    environment:
      # Used by the entrypoint script !IMPORTANT
      - FRONTEND_HOST=prod-frontend
    depends_on:
      - prod-frontend
    profiles: ["prod"]
    networks:
      - prod_network
    restart: unless-stopped


  # PostgreSQL Database Development
  dev-database:
    build:
      context: ./app/database
      dockerfile: Dockerfile
    env_file:
      - ./infra/env.d/dev
      - ./infra/env.d/database
    volumes:
      - .data/postgres:/var/lib/postgresql/data
      # Initialization script(s), runs only on first creation
      - ./infra/initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    shm_size: 1gb
    profiles: ["dev"]
    networks:
      - dev_network
    restart: no

  # FastAPI Backend Development
  dev-backend:
    build:
      context: ./app/backend
      dockerfile: Dockerfile
    env_file:
      - ./infra/env.d/dev
      - ./infra/env.d/ai
      - ./infra/env.d/backend
      - ./infra/env.d/database
      - ./infra/env.d/.private
    volumes:
      - ./app/backend:/app
      - .data/cache/dspy:/cache/dspy
    ports:
      - "8000:8000"
    command: sh -c "
        cd /app
        && uvicorn main:app --host 0.0.0.0 --port 8000 --reload
      " # Add --reload for development
    depends_on:
      - dev-database
    profiles: ["dev"]
    networks:
      - dev_network
    restart: no

  # SvelteKit Frontend Development
  dev-frontend:
    # Use Debian for development
    image: node:23-bookworm-slim
    ports:
      - "3000:3000"
    env_file:
      - ./infra/env.d/dev
      - ./infra/env.d/backend
      - ./infra/env.d/frontend
      - ./infra/env.d/.private
    volumes:
      # Mount local code to reload automatically during development,
      # and save installation files to local
      - ./app/frontend:/app
    command: sh -c "
        cd /app
        && npm install
        && npm run dev -- --host --port 3000
      "
    depends_on:
      - dev-backend
    profiles: ["dev"]
    networks:
      - dev_network
    restart: no

  # Nginx Reverse Proxy Development
  dev-nginx:
    build:
      context: ./app/nginx
      dockerfile: Dockerfile
    ports:
      - '80:80'
    volumes:
      # Mount the Nginx configuration file read-only
      - ./app/nginx/nginx.template.conf:/etc/nginx/templates/nginx.template.conf:ro
    environment:
      # Used by the entrypoint script !IMPORTANT
      - FRONTEND_HOST=dev-frontend
    depends_on:
      - dev-frontend
    profiles: ["dev"]
    networks:
      - dev_network
    restart: no

    
networks:
  dev_network:
    driver: bridge
  prod_network:
    driver: bridge